entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  file:
    directory: "/etc/traefik/dynamic"

api:
  dashboard: true

log:
  level: INFO

certificatesResolvers:
  letsencrypt:
    acme:
      email: you@example.com
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web