---
- hosts: webserver
  become: yes

  tasks:
    - name: Mettre à jour les paquets
      yum:
        name: "*"
        state: latest

    - name: Installer Nginx
      yum:
        name: nginx
        state: present

    - name: Créer un fichier index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Welcome to clemuscle land!</title>
          </head>
          <body>
            <h1>Success: The Nginx server is wooooorking!</h1>
          </body>
          </html>
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'