---
- hosts: webserver
  become: yes

  tasks:
    - name: Mettre à jour les paquets
      yum:
        name: "*"
        state: latest

    - name: Installer Nginx
      yum:
        name: nginx
        state: present

    - name: Enable Nginx
      service:
        name: nginx
        enabled: yes

    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Ajout du fichier index.html
      copy:
        src: ./nginx/index.html
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'