version: '3'

services:
  traefik:
    image: docker.io/traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/etc/traefik/acme.json
      - ./dynamic:/etc/traefik/dynamic
    command:
      - --api.insecure=true
      - --log.level=INFO
    restart: unless-stopped