global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

rule_files:
  # Fichiers de règles d'alerte
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] # Module HTTP pour vérifier les 200 OK
    static_configs:
      - targets:
          - http://example.com # Remplacez par l'URL à surveiller
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'wazuh'
    static_configs:
      - targets: ['wazuh-manager:55000']
